services:
  jekyll:
    build: .
    container_name: danleyb2-blog
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    restart: always
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload
